### PR TITLE
Build mypy with mypyc for increased performance

### PR DESCRIPTION
**Pull request by cauebs**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

I'm setting an environment variable checked in mypy's `setup.py` to enable building with mypyc, a Python compiler. It's included in mypy's tarball, we just need to have its dependencies installed in the environment and the environment variable set.

I've also added a test to check if the build artifacts contain the binary files, so as to disallow builds without mypyc.

The performance improvement is very substancial (around 4 times faster, according to [mypy's README](https://github.com/python/mypy/#compiled-version-of-mypy)), and the behaviour is supposed to be identical.

This removes the `noarch` label, since the binaries are platform-specific.

I added a `--no-deps` to install dependencies strictly using conda. Let me know if that shouldn't be the case.

Note: builds take about 10 times longer, unfortunately.

### CODE REVIEW

**Comment by cauebs** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Failures:

```
  build/__native_8c8c5116bc4884237d33.c: At top level:
  cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
  cc1: error: unrecognized command line option '-Wno-unused-command-line-argument' [-Werror]
  cc1: all warnings being treated as errors
  error: command '/home/conda/feedstock_root/build_artifacts/mypy_1617292792875/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1

```

Not sure what's the solution here. Perhaps @ocefpaf can give a hand?

**Comment by ocefpaf** [comment]
> Not sure what's the solution here. Perhaps @ocefpaf can give a hand?

@nehaljwani is on the case! BTW, are you upstreaming that patch? If so let's add the PR number here to track it.

**Comment by nehaljwani** [comment]
`-Wno-unknown-warning-option` and `-Wno-unused-command-line-argument` seem to be recognized only by Clang, not GCC. Upstreaming the patch will require some work :)

**Pull request merged**
